# 1 My Bike Trip in Sisters

I was looking forward to this ride. It was a beautiful sunny day. The air was sweet with the aroma of the trees. My bike was ready to go. I had mapped out a ride that would take me through the beautiful scenery of Central Oregon. It wasn’t to be too long. I was still in the initial stages of preparing for the Seattle to Portland bike ride. I had a long way to go before I was ready for that nearly 200 mile ride. I had ridden the Seattle to Portland bike ride six or seven years ago. It was a blast. I did it by myself but it was still quite a bit of fun. There’s nothing like owning the road with thousands of other cyclists. And it was physically taxing  enough that it felt like a real achievement.

The years since that bike ride I had let myself go. I had gained quite a bit of weight. I am 6’2” tall, and in college I weighed 185 pounds. Recently I had weighed 265 pounds. I had found myself tiring easily, breathless at the top of the long flight of stairs, and little to no energy at the end of the day. I felt like I was in the worst shape of my life. I had allowed the responsibilities and the time commitments of work as an academic urologist to encourage me to eat poorly and not exercise. As as a husband and father of four I also felt I was not being a good example. So when my best friend from college and high school called from Colorado to suggest we do the Seattle to Portland bike ride together, I saw it as an opportunity to kickstart a return to fitness levels of my past.

I was a couple of months into my training. I had changed my diet back to vegan which I had done in the past for about a year to correct a slightly elevated cholesterol level. I had also been riding indoors on my bike on a trainer and it felt good other than a bit of indigestion at times while hunched over on the bike. This diet and exercise at arty help me lose almost 20 pounds. But I was very excited to finally hit the road and there’s no better place than Sisters, Oregon. Sisters is a small town just beyond the Santiam pass. It was a cowboy town with a beautiful Main Street with antique shops and bookstores and healthy restaurants. Terri and I had purchased a small cabin in the woods just outside of Sisters, Oregon. I returned to the cabin after working at our urology clinic in Bend, Oregon yesterday. It was a long clinic and its always refreshing to return to the quiet and stillness of the woods, after having spent the day pouring myself out to the patients something I really enjoyed but being a natural introvert, took a great deal of energy for me.

So here I was now poised to take off on my ride enjoy the sunshine in a burn my legs. It began wonderfully the wind at my bank spinning easily through a mostly flat section for a mile or two. And then a turn to the east things changed. Riding more into the wind and slightly uphill I adjusted my gearing appropriately. About 30 seconds later, I felt that indigestion, reflux I figured, but this time it seemed a bit more severe. And it continued to increase. It became clear to me that it was not reflux. It became clear to me that I had been ignoring, rationalizing away the symptoms that I had had. None of the "indigestion" that I've been having on the bike were gastrointestinal in origin. The exhaustion at the end of my work days. The breathlessness at the top of the stairs. My untreated elevated cholesterol. My family history. And now a pain that had grown to clearly anginal pain on exertion on my bike in the middle of rural central Oregon, and I was totally alone. Once I had fully process what was going on I came to a screeching halt. I did not want to drop dead alone on a remote highway however beautiful it was. I knew that there was a small clinic in town. I'd never been there but passed it many times. I walked my bike a bit after a long rest. I then hopped back on my bike and peddled very easily into the main freeway and up to the clinic. I figured it would be good to get an EKG and perhaps a troponin level just to make sure I had not had an MI. Unfortunately the clinic was closed. It was not an urgent care clinic but a family practice and it was Saturday. I tried to call Terri. I left a message. I knew I needed to pack up, head back to Portland, and get my heart evaluated. I had a lot to think about on the three-hour drive back home.
